apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-web
  namespace: ${K8S_NAMESPACE}
  labels:
    app: weather-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-web
  template:
    metadata:
      labels:
        app: weather-web
    spec:
      containers:
        - name: weather-web
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

