apiVersion: v1
kind: Service
metadata:
  name: weather-web
  namespace: ${K8S_NAMESPACE}
  labels:
    app: weather-web
spec:
  selector:
    app: weather-web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

